install: travis_wait 15 mvn install
language: python
python:
  - "2.7"
  - "3.7"
env:
  - BML_TESTS="05"
  - BML_TESTS="35 33"
  - BML_TESTS="01 02 03 04 06 07 08 09 10 11 12"
  - BML_TESTS="36"
  - BML_TESTS="13 14 15 16 17 18 19 20 21 22 24 25 26 27 28 29 30 31 32 34 39 43"
  - BML_TESTS="23 37 38 40 41 45"
  - BML_TESTS="42 44"
install:
  - pip install numpy
  - pip install scipy
  - pip install cython
  - pip install pystemmer==2.0.0
  - pip install .
script:
  - export TESTS=$(for t in $BML_TESTS; do ls bigml/tests/*$t*;done|paste -sd ",")
  - echo $TESTS
  - python setup.py nosetests --nocapture --tests=$TESTS
