name: "Python bindings tests 23"

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

jobs:
  tests-23:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.11]
    env:
        BIGML_USERNAME: ${{ secrets.BIGML_USERNAME }}
        BIGML_API_KEY: ${{ secrets.BIGML_API_KEY }}
        BIGML_ORGANIZATION: ${{ secrets.BIGML_ORGANIZATION }}
        BIGML_EXTERNAL_CONN_HOST: ${{ secrets.BIGML_EXTERNAL_CONN_HOST }}
        BIGML_EXTERNAL_CONN_PORT: ${{ secrets.BIGML_EXTERNAL_CONN_PORT }}
        BIGML_EXTERNAL_CONN_DB: ${{ secrets.BIGML_EXTERNAL_CONN_DB }}
        BIGML_EXTERNAL_CONN_USER: ${{ secrets.BIGML_EXTERNAL_CONN_USER }}
        BIGML_EXTERNAL_CONN_PWD: ${{ secrets.BIGML_EXTERNAL_CONN_PWD }}
        BIGML_DELTA: ${{ env.BIGML_DELTA }}

    steps:
    - name: Install packages
      uses: actions/checkout@v3
    - run: |
        pip install .[full]

    - name: Run tests *23 03 37 35 47 48 49 99*
      run: |
        pip3 install pytest
        export TESTS=$(for t in "23" "03" "37" "35" "47" "48" "49" "99"; do ls bigml/tests/*$t*.py;done|paste -sd " ")
        echo $TESTS
        pytest -s $TESTS
